name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      
      # general model
      - name: general
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          
          # isocalendar
          plugin_isocalendar: yes
          
          # language
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
            
          config_order: base.header, isocalendar, language, base.repositories
      
      # achievement
      - name: achievement
        uses: lowlighter/metrics@latest
        with:
          filename: achievement.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          
          # achievement
          plugin_achievements: yes
          plugin_achievements_display: compact
      
      # people & activity
      - name: people
        uses: lowlighter/metrics@latest
        with:
          filename: people.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          
          # activity
          plugin_activity: yes
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          
          # people
          plugin_people: yes
          
