name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: matrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # isocalendar
          plugin_isocalendar: yes
          
          # activity
          plugin_activity: yes
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          
          # language
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          
          
